spring:
  application:
    name:employee-service
  datasource:
    url: jdbc:h2:mem:employees
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
      continue-on-error: true

logging:
  level:
    root: ERROR
    com.siscon.employee: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    enabled: true
    name: mi-aplicacion.log
    max-size: 10MB
    max-history: 5